### ISSUE TITLE
Error - hashes do not match.

### ISSUE THREAD

**Issue by mescon** [AdmiringWorm/chocolatey-packages#387] opened 2022-08-03 11:29 UTC
**Describe the bug**
Hash mismatch, preventing installation of updated package.

**To Reproduce**

1. cup all -y

**Expected behavior**
Expected the updated package to be installed.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Chocolatey version: 1.1.0
- Package version: 5.8.70

**Chocolatey Install/Uninstall log**
```
You have master-pdf-editor v5.8.63 installed. Version 5.8.70 is available based on your source(s).
Progress: Downloading master-pdf-editor 5.8.70... 100%

master-pdf-editor v5.8.70 [Approved]
master-pdf-editor package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'E630CE1C1BA2F44A334521A373195BA31B55BCAFD84F5D2EBD079D59ABA125D3FD660916B12661986C4B632243602DAFEF89E28C3A89C2CB28F26801801D5AC1'.
Downloading master-pdf-editor
  from 'https://code-industry.net/public/MasterPDFEditor-setup.exe'
Progress: 100% - Completed download of C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe (33.44 MB).
Download of MasterPDFEditor-setup.exe (33.44 MB) completed.
Error - hashes do not match. Actual value was 'E630CE1C1BA2F44A334521A373195BA31B55BCAFD84F5D2EBD079D59ABA125D3FD660916B12661986C4B632243602DAFEF89E28C3A89C2CB28F26801801D5AC1'.
ERROR: Checksum for 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe' did not meet '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of master-pdf-editor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1'.
 See log for details.
 ```

**Additional debug**
```
2022-08-03 13:11:04,013 17448 [INFO ] - VERBOSE: Importing alias 'Start-ChocolateyProcess'.
2022-08-03 13:11:04,029 17448 [DEBUG] - ---------------------------Script Execution---------------------------
2022-08-03 13:11:04,031 17448 [DEBUG] - Running 'ChocolateyScriptRunner' for master-pdf-editor v5.8.70 with packageScript 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\master-pdf-editor', installArguments: '', packageParameters: '',
2022-08-03 13:11:04,033 17448 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1'
2022-08-03 13:11:04,060 17448 [DEBUG] - Running Install-ChocolateyPackage -silentArgs '/SILENT /NORESTART /SUPPRESSMSGBOXES /SP- /LOG="C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor.5.8.70.InnoInstall.log"' -checksumType 'sha512' -url 'https://code-industry.net/public/MasterPDFEditor-setup.exe' -checksum '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' -packageName 'master-pdf-editor' -validExitCodes '0' -fileType 'exe' 
2022-08-03 13:11:04,075 17448 [DEBUG] - Running Get-ChocolateyWebFile -packageName 'master-pdf-editor' -fileFullPath 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\master-pdf-editorInstall.exe' -url 'https://code-industry.net/public/MasterPDFEditor-setup.exe' -url64bit '' -checksum '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' -checksumType 'sha512' -checksum64 '' -checksumType64 '' -options 'System.Collections.Hashtable' -getOriginalFileName 'True' 
2022-08-03 13:11:04,082 17448 [DEBUG] - Running Get-ProcessorBits -compare '64' 
2022-08-03 13:11:04,088 17448 [DEBUG] - CPU is 64 bit
2022-08-03 13:11:04,098 17448 [DEBUG] - Running Get-WebFileName -url 'https://code-industry.net/public/MasterPDFEditor-setup.exe' -defaultName 'master-pdf-editorInstall.exe' 
2022-08-03 13:11:04,396 17448 [DEBUG] - Using response url to determine file name. 'https://code-industry.net/public/MasterPDFEditor-setup.exe'
2022-08-03 13:11:04,398 17448 [DEBUG] - File name determined from url is 'MasterPDFEditor-setup.exe'
2022-08-03 13:11:04,408 17448 [DEBUG] - Running Get-WebHeaders -url 'https://code-industry.net/public/MasterPDFEditor-setup.exe' -ErrorAction 'Stop' 
2022-08-03 13:11:04,410 17448 [DEBUG] - Setting the UserAgent to 'chocolatey command line'
2022-08-03 13:11:04,410 17448 [DEBUG] - Request Headers:
2022-08-03 13:11:04,413 17448 [DEBUG] -   'Accept':'*/*'
2022-08-03 13:11:04,414 17448 [DEBUG] -   'User-Agent':'chocolatey command line'
2022-08-03 13:11:04,534 17448 [DEBUG] - Response Headers:
2022-08-03 13:11:04,536 17448 [DEBUG] -   'Connection':'keep-alive'
2022-08-03 13:11:04,537 17448 [DEBUG] -   'Accept-Ranges':'bytes'
2022-08-03 13:11:04,538 17448 [DEBUG] -   'Content-Length':'35061592'
2022-08-03 13:11:04,538 17448 [DEBUG] -   'Content-Type':'application/octet-stream'
2022-08-03 13:11:04,539 17448 [DEBUG] -   'Date':'Wed, 03 Aug 2022 11:11:02 GMT'
2022-08-03 13:11:04,540 17448 [DEBUG] -   'ETag':'"62c2fc25-216ff58"'
2022-08-03 13:11:04,540 17448 [DEBUG] -   'Last-Modified':'Mon, 04 Jul 2022 14:41:41 GMT'
2022-08-03 13:11:04,541 17448 [DEBUG] -   'Server':'nginx/1.18.0 (Ubuntu)'
2022-08-03 13:11:04,549 17448 [INFO ] - File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
2022-08-03 13:11:04,556 17448 [DEBUG] - Running Get-ChecksumValid -file 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe' -checksum '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' -checksumType 'sha512' -originalUrl 'https://code-industry.net/public/MasterPDFEditor-setup.exe' -ErrorAction 'Stop' 
2022-08-03 13:11:04,561 17448 [DEBUG] - checksum.exe found at 'C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
2022-08-03 13:11:04,561 17448 [DEBUG] - Executing command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4" -t="sha512" -f="C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe"]
2022-08-03 13:11:05,086 17448 [DEBUG] - Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4" -t="sha512" -f="C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe"] exited with '1'.
2022-08-03 13:11:05,100 17448 [DEBUG] - Existing file failed checksum. Will be redownloaded from url.
2022-08-03 13:11:05,102 17448 [INFO ] - Downloading master-pdf-editor 
  from 'https://code-industry.net/public/MasterPDFEditor-setup.exe'
2022-08-03 13:11:05,110 17448 [DEBUG] - Running Get-WebFile -url 'https://code-industry.net/public/MasterPDFEditor-setup.exe' -fileName 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe' -options 'System.Collections.Hashtable' 
2022-08-03 13:11:05,111 17448 [DEBUG] - Setting request timeout to  30000
2022-08-03 13:11:05,112 17448 [DEBUG] - Setting read/write timeout to  2700000
2022-08-03 13:11:05,112 17448 [DEBUG] - Setting the UserAgent to 'chocolatey command line'
2022-08-03 13:11:05,294 17448 [DEBUG] - Downloading https://code-industry.net/public/MasterPDFEditor-setup.exe to C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe
2022-08-03 13:11:08,880 17448 [INFO ] - 
2022-08-03 13:11:08,882 17448 [INFO ] - Download of MasterPDFEditor-setup.exe (33.44 MB) completed.
2022-08-03 13:11:11,912 17448 [DEBUG] - No runtime virus checking built into FOSS Chocolatey. Check out Pro/Business - https://chocolatey.org/compare
2022-08-03 13:11:11,913 17448 [DEBUG] - Verifying package provided checksum of '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' for 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe'.
2022-08-03 13:11:11,914 17448 [DEBUG] - Running Get-ChecksumValid -file 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe' -checksum '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' -checksumType 'sha512' -originalUrl 'https://code-industry.net/public/MasterPDFEditor-setup.exe' 
2022-08-03 13:11:11,916 17448 [DEBUG] - checksum.exe found at 'C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
2022-08-03 13:11:11,916 17448 [DEBUG] - Executing command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4" -t="sha512" -f="C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe"]
2022-08-03 13:11:12,015 17448 [DEBUG] - Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4" -t="sha512" -f="C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe"] exited with '1'.
2022-08-03 13:11:12,019 17448 [ERROR] - ERROR: Checksum for 'C:\Users\mescon\AppData\Local\Temp\chocolatey\master-pdf-editor\5.8.70\MasterPDFEditor-setup.exe' did not meet '44FAAA5EAE7A54F6699138B7CE42D31EB52BBC9B69ECD35DFC41A6148CD91081E3F91A5A0F6F26FB9D03F09552FF086608E2E595795BE6CE43FB88E11CA930A4' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
2022-08-03 13:11:12,022 17448 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
2022-08-03 13:11:12,024 17448 [DEBUG] - Calling command ['"C:\windows\System32\shutdown.exe" /a']
2022-08-03 13:11:12,044 17448 [DEBUG] - Command ['"C:\windows\System32\shutdown.exe" /a'] exited with '1116'
2022-08-03 13:11:12,066 17448 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\master-pdf-editor'
2022-08-03 13:11:12,067 17448 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\master-pdf-editor\master-pdf-editor.nupkg'
  with checksum 'E81FA8C6A8525A9C96BB06CCBC7E59A7'
2022-08-03 13:11:12,068 17448 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\master-pdf-editor\master-pdf-editor.nuspec'
  with checksum '78DEB1E10A37BD1F50A294B87982F28A'
2022-08-03 13:11:12,069 17448 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1'
  with checksum '1A5E4801493F27093DFB045DFCD408E4'
2022-08-03 13:11:12,069 17448 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyUninstall.ps1'
  with checksum 'DF5E59405F3B629AB5EB81FF5CD2C2FC'
2022-08-03 13:11:12,076 17448 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\master-pdf-editor.5.8.70\.arguments".
2022-08-03 13:11:12,077 17448 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\master-pdf-editor.5.8.70\.extra".
2022-08-03 13:11:12,077 17448 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\master-pdf-editor.5.8.70\.version".
2022-08-03 13:11:12,077 17448 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\master-pdf-editor.5.8.70\.sxs".
2022-08-03 13:11:12,078 17448 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\master-pdf-editor.5.8.70\.pin".
2022-08-03 13:11:12,080 17448 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\master-pdf-editor".
2022-08-03 13:11:12,082 17448 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2022-08-03 13:11:12,083 17448 [ERROR] - The upgrade of master-pdf-editor was NOT successful.
2022-08-03 13:11:12,085 17448 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\master-pdf-editor\tools\chocolateyInstall.ps1'.
 See log for details.
2022-08-03 13:11:12,086 17448 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\master-pdf-editor'
 to 'C:\ProgramData\chocolatey\lib-bad\master-pdf-editor'
2022-08-03 13:11:14,094 17448 [DEBUG] - Attempting rollback
2022-08-03 13:11:14,095 17448 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib-bkp\master-pdf-editor'
 to 'C:\ProgramData\chocolatey\lib\master-pdf-editor'
2022-08-03 13:11:16,108 17448 [DEBUG] - Attempting to delete file "C:\Users\mescon\AppData\Local\NuGet\Cache\master-pdf-editor.5.8.70.nupkg".
```

**Comment by AdmiringWorm** [comment] 2023-03-29 07:06
Duplicate of #386

**Closed by AdmiringWorm** 2023-03-29 07:06 UTC
